# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


StationInfo.delete_all
StationInfo.create(name:"延中绿地",alias_name:"",site_number:"99635",district:"市区",address:"上海市静安区、卢湾区、黄浦区三区交界处延中绿地",lon: 121.441,lat: 31.2236,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"闸北公园",alias_name:"",site_number:"99630",district:"市区",address:"上海市闸北区共和新路1555号闸北公园",lon: 121.453,lat: 31.2725,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"人民公园",alias_name:"",site_number:"99633",district:"市区",address:"上海市黄浦区南京西路75号人民公园",lon: 121.469,lat: 31.2338,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"康健公园",alias_name:"",site_number:"99625",district:"市区",address:"上海市徐汇区康健路1号",lon: 121.418,lat: 31.166,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"鲁迅公园",alias_name:"",site_number:"99639",district:"市区",address:"上海市虹口区四川北路 鲁迅公园",lon: 121.479,lat: 31.2753,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"甘泉公园",alias_name:"",site_number:"99645",district:"市区",address:"上海市普陀区西乡路100号",lon: 121.423,lat: 31.2692,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"和平公园",alias_name:"",site_number:"",district:"市区",address:"上海市虹口区大连路1131号 和平公园",lon: 121.295,lat: 31.1621,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"金桥",alias_name:"",site_number:"98604",district:"浦东",address:"上海市浦东新区川桥路850号近金港路城管金桥分队大院内",lon: 121.601,lat: 31.2481,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"张江华师大二附中",alias_name:"",site_number:"98600",district:"浦东",address:"上海市浦东新区晨辉路555号近科苑路",lon: 121.586,lat: 31.2019,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"川沙站",alias_name:"",site_number:"98601",district:"浦东",address:"上海市浦东新区川黄路1号桥东首(过桥左侧锦川路进200米川沙气象站旧址)",lon: 121.705,lat: 31.1892,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"凌桥",alias_name:"",site_number:"98602",district:"浦东",address:"上海市浦东新区草高公路左转草庵头路近公安高等专科学校",lon: 121.512,lat: 31.3814,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"陆家嘴",alias_name:"",site_number:"98608",district:"浦东",address:"上海市浦东新区银城中路陆家嘴绿地近世纪大道草坪",lon: 121.506,lat: 31.1967,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"防汛前线指挥部",alias_name:"",site_number:"98606",district:"浦东",address:"上海市浦东新区曹路镇兴东村东首 人民塘路近小华江路",lon: 121.7,lat: 31.2922,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"西沟",alias_name:"",site_number:"98623",district:"浦东",address:"上海市浦东新区长岛路350号近兰城路",lon: 121.583,lat: 31.2667,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"女儿泾水闸",alias_name:"",site_number:"98413",district:"闵行",address:"上海市闵行区江川路",lon: 121.322,lat: 30.9864,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"旗忠网球场",alias_name:"",site_number:"98417",district:"闵行",address:"上海市闵行区元江路",lon: 121.353,lat: 31.0408,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"虹桥",alias_name:"",site_number:"98409",district:"闵行",address:"上海市闵行区万源路",lon: 121.379,lat: 31.0208,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"颛桥",alias_name:"",site_number:"98405",district:"闵行",address:"上海市闵行区北吴路",lon: 121.419,lat: 31.0492,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"七宝",alias_name:"",site_number:"98407",district:"闵行",address:"上海市闵行区吴中路2579号",lon: 121.344,lat: 31.1642,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"大治河西闸",alias_name:"",site_number:"98408",district:"闵行",address:"上海市闵行区闸航路",lon: 121.5,lat: 31.0206,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"曹家港水闸",alias_name:"",site_number:"98404",district:"闵行",address:"上海市闵行区金都路龙吴路口",lon: 121.449,lat: 31.0969,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"石洞口",alias_name:"",site_number:"99502",district:"宝山",address:"上海市宝山区盛石路石洞口码头",lon: 121.417,lat: 31.4683,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"罗店度假村",alias_name:"",site_number:"98311",district:"宝山",address:"上海市宝山区联杨路3888号东方假日田园",lon: 121.32,lat: 31.385,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"防汛办",alias_name:"",site_number:"98301",district:"宝山",address:"上海市宝山区密山路10号",lon: 121.4,lat: 31.4,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"月浦镇",alias_name:"",site_number:"98305",district:"宝山",address:"上海市宝山区月罗公路200号",lon: 121.417,lat: 31.4219,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"淞南公园",alias_name:"",site_number:"98304",district:"宝山",address:"上海市宝山区虎林路100号甲泗塘小学内",lon: 121.484,lat: 31.3439,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"顾村",alias_name:"",site_number:"98307",district:"宝山",address:"上海市宝山区泰和西路3431号",lon: 121.402,lat: 31.3514,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"月浦镇农副公司",alias_name:"",site_number:"98306",district:"宝山",address:"上海市宝山区古莲路271号",lon: 121.399,lat: 31.4519,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"朱桥",alias_name:"",site_number:"98801",district:"嘉定",address:"上海市嘉定区朱桥养鸽场",lon: 121.183,lat: 31.3833,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"浏河",alias_name:"",site_number:"98803",district:"嘉定",address:"上海市嘉定区华亭现代农业园区",lon: 121.286,lat: 31.485,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"毛桥",alias_name:"",site_number:"98806",district:"嘉定",address:"上海市嘉定区唐行毛桥村",lon: 121.317,lat: 31.3333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"F1赛场",alias_name:"",site_number:"98809",district:"嘉定",address:"上海市嘉定区F1赛车场",lon: 121.233,lat: 31.3333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"徐行劳动村",alias_name:"",site_number:"98807",district:"嘉定",address:"上海市嘉定区徐行劳动村",lon: 121.317,lat: 31.45,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"马陆大裕村",alias_name:"",site_number:"98808",district:"嘉定",address:"上海市嘉定区马陆大裕村",lon: 121.317,lat: 31.3833,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"侯家镇",alias_name:"",site_number:"98001",district:"崇明",address:"侯家镇原老站草地屋顶",lon: 121.454,lat: 31.615,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"明珠湖",alias_name:"",site_number:"98005",district:"崇明",address:"明珠湖景区草地",lon: 121.196,lat: 31.7281,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"森林公园",alias_name:"",site_number:"98003",district:"崇明",address:"森林公园内草地",lon: 121.479,lat: 31.6894,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"崇明新河",alias_name:"",site_number:"98013",district:"崇明",address:"新河水闸屋顶",lon: 121.518,lat: 31.5708,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"现代农业园区",alias_name:"",site_number:"98008",district:"崇明",address:"现代园区基地草地",lon: 121.798,lat: 31.5906,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"崇明陈家镇",alias_name:"",site_number:"98010",district:"崇明",address:"陈家镇原老站屋顶",lon: 121.799,lat: 31.5,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"六灶中学",alias_name:"",site_number:"98500",district:"浦东",address:"鹿溪路校内文达工作室近周祝公路",lon: 121.694,lat: 31.1164,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"雷达站",alias_name:"",site_number:"98506",district:"浦东",address:"南滨公路（军港公路）大转盘左转至通源东路过桥右侧雷达站内",lon: 121.883,lat: 31.0076,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新场中学",alias_name:"",site_number:"98505",district:"浦东",address:"东后大街152号 新奉公路至石笋街左转到底再左转，对面有个耶稣堂，主机位于小楼中铁门里",lon: 121.645,lat: 31.0247,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"沧海桑田",alias_name:"",site_number:"98617",district:"浦东",address:"上海市浦东新区滨海旅游度假区通源东路",province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"芦潮港",alias_name:"",site_number:"98502",district:"浦东",address:"上海市浦东新区芦潮港镇政府",lon: 121.849,lat: 30.8592,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"临港新城",alias_name:"",site_number:"98521",district:"浦东",address:"上海市浦东新区滴水湖环湖西一路99号",lon: 121.921,lat: 30.905,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"朱行",alias_name:"",site_number:"98108",district:"金山",address:"金山区朱行水厂中压泵站",lon: 121.34,lat: 30.8417,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"漕泾",alias_name:"",site_number:"98101",district:"金山",address:"金山区漕泾人民政府",lon: 121.406,lat: 30.7961,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"兴塔",alias_name:"",site_number:"98106",district:"金山",address:"金山区亭枫公路6728号",lon: 121.042,lat: 30.8728,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"朱家角",alias_name:"",site_number:"98703",district:"青浦",address:"青浦区朱家角镇新镇区泽溪路88号朱家角高级中学",lon: 121.037,lat: 31.105,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"商榻镇",alias_name:"",site_number:"98700",district:"青浦",address:"青浦区金泽镇商浜村长连泾港北区管理中心商周公路南200米",lon: 120.9,lat: 31.12,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"练塘镇",alias_name:"",site_number:"98701",district:"青浦",address:"青浦区练塘镇农业中心科技创新基地朱枫公路东500米",lon: 121.03,lat: 30.97,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"华新",alias_name:"",site_number:"98702",district:"青浦",address:"青浦区华新镇纪鹤路1858号凌家村行政大楼",lon: 121.23,lat: 31.25,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"水上运动场",alias_name:"",site_number:"98704",district:"青浦",address:"青浦区朱家角镇盈朱路289号水上运动场",lon: 121.004,lat: 31.1128,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"现代农业园区",alias_name:"",site_number:"98705",district:"青浦",address:"青浦区练塘镇蒸富路100号现代农业园区",lon: 121.018,lat: 30.9636,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"九亭",alias_name:"",site_number:"98211",district:"松江",address:"九亭气象园区",lon: 121.284,lat: 31.1408,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"泖港",alias_name:"",site_number:"98216",district:"松江",address:"泖港镇腰泾村叶新公路999号",lon: 121.175,lat: 30.9364,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"农业中心",alias_name:"",site_number:"98214",district:"松江",address:"松金公路9969号",lon: 121.238,lat: 30.9979,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"西部渔村",alias_name:"",site_number:"98215",district:"松江",address:"昆泖公路西到底",lon: 121.128,lat: 30.9347,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"泰晤士小镇",alias_name:"",site_number:"98254",district:"松江",address:"泰晤士管委会4号楼",lon: 121.192,lat: 31.0351,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"石湖荡",alias_name:"",site_number:"98208",district:"松江",address:"镇政府",lon: 121.112,lat: 30.9867,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"车墩",alias_name:"",site_number:"98205",district:"松江",address:"车墩镇政府",lon: 121.31,lat: 31.0171,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"化工分区",alias_name:"",site_number:"98902",district:"奉贤",address:"西部污水处理场",lon: 121.703,lat: 30.8169,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"庄行",alias_name:"",site_number:"98912",district:"奉贤",address:"庄行镇镇政府",lon: 121.393,lat: 30.9037,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"燎原",alias_name:"",site_number:"98910",district:"奉贤",address:"奉城镇共耕村(农户）",lon: 121.649,lat: 30.8846,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"头桥",alias_name:"",site_number:"98911",district:"奉贤",address:"头桥社区办事处",lon: 121.638,lat: 30.9492,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"青村",alias_name:"",site_number:"98915",district:"奉贤",address:"青村镇农科站",lon: 121.563,lat: 30.9273,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"泰日",alias_name:"",site_number:"98916",district:"奉贤",address:"大叶公路5555号",lon: 121.514,lat: 30.9786,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"黄兴绿地",alias_name:"",site_number:"99603",district:"市区",address:"杨浦区黄兴公园",lon: 121.523,lat: 31.2928,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"康健公园",alias_name:"",site_number:"99625",district:"市区",address:"徐汇区康健公园",lon: 121.25,lat: 31.0958,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"上海动物园",alias_name:"",site_number:"99626",district:"市区",address:"上海动物园",lon: 121.361,lat: 31.1939,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新虹桥花园",alias_name:"",site_number:"99627",district:"市区",address:"新虹桥花园",lon: 121.399,lat: 31.2021,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"徐家汇公园",alias_name:"",site_number:"99628",district:"市区",address:"徐家汇公园",lon: 121.437,lat: 31.1996,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"上海植物园",alias_name:"",site_number:"99629",district:"市区",address:"上海植物园",lon: 121.442,lat: 31.15,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"三泉公园",alias_name:"",site_number:"99331",district:"市区",address:"三泉公园",lon: 121.442,lat: 31.318,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"蓬莱公园",alias_name:"",site_number:"99632",district:"市区",address:"蓬莱公园",lon: 121.487,lat: 31.2083,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"静安公园",alias_name:"",site_number:"99634",district:"市区",address:"静安公园",lon: 121.44,lat: 31.2236,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"襄阳公园",alias_name:"",site_number:"99636",district:"市区",address:"襄阳公园",lon: 121.452,lat: 31.2195,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"复兴公园",alias_name:"",site_number:"99637",district:"市区",address:"复兴公园",lon: 121.464,lat: 31.2186,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"大宁灵石公园",alias_name:"",site_number:"99640",district:"市区",address:"大宁灵石公园",lon: 121.435,lat: 31.2773,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"四平科技公园",alias_name:"",site_number:"99641",district:"市区",address:"四平科技公园",lon: 121.503,lat: 31.2891,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"淮海公园",alias_name:"",site_number:"99642",district:"市区",address:"淮海公园",lon: 121.473,lat: 31.2254,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"曲阳公园",alias_name:"",site_number:"99643",district:"市区",address:"曲阳公园",lon: 121.483,lat: 31.2882,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"中山公园",alias_name:"",site_number:"99644",district:"市区",address:"中山公园",lon: 121.412,lat: 31.2247,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"甘泉公园",alias_name:"",site_number:"99645",district:"市区",address:"甘泉公园",lon: 121.252,lat: 31.1609,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"长寿公园",alias_name:"",site_number:"99646",district:"市区",address:"长寿公园",lon: 121.435,lat: 31.2442,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"长风公园",alias_name:"",site_number:"99647",district:"市区",address:"长风公园",lon: 121.393,lat: 31.2233,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"未来岛公园",alias_name:"",site_number:"99648",district:"市区",address:"未来岛公园",lon: 121.371,lat: 31.267,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"曹杨公园",alias_name:"",site_number:"",district:"市区",address:"曹杨公园",lon: 121.242,lat: 31.143,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"天山公园",alias_name:"",site_number:"",district:"市区",address:"天山公园",lon: 121.244,lat: 31.1248,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"共青森林公园",alias_name:"",site_number:"",district:"市区",address:"共青森林公园",lon: 121.323,lat: 31.1927,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"杨浦公园",alias_name:"",site_number:"",district:"市区",address:"杨浦公园",lon: 121.32,lat: 31.1655,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"共和新路_中山北路",alias_name:"",site_number:"",district:"市区",address:"共和新路1238号铁医学院",lon: 121.261,lat: 31.1737,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"延安西路_中山西路",alias_name:"",site_number:"",district:"市区",address:"中山西路435号",lon: 121.243,lat: 301.0,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"东体育会路_虹口体育馆",alias_name:"",site_number:"",district:"市区",address:"东体育会路715号",lon: 121.29,lat: 31.1714,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"黄浦公园",alias_name:"",site_number:"99103",district:"市区",address:"外滩黄浦公园水文站",lon: 121.487,lat: 31.2432,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"南漕东",alias_name:"",site_number:"99560",district:"市区",address:"长江口南支航道",lon: 122.101,lat: 30.9972,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"小洋山东",alias_name:"",site_number:"98508",district:"海洋台",address:"小洋山东",lon: 122.069,lat: 30.6219,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"小洋山西",alias_name:"",site_number:"98509",district:"海洋台",address:"小洋山西",lon: 122.048,lat: 30.6336,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"洋山三期",alias_name:"",site_number:"98518",district:"海洋台",address:"洋山三期",lon: 122.091,lat: 30.61,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"下三星",alias_name:"",site_number:"",district:"海洋台",address:"下三星",lon: 122.313,lat: 30.2606,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"岱山航标处",alias_name:"",site_number:"99132",district:"海洋台",address:"岱山航标处",lon: 122.186,lat: 30.2878,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"小衢山",alias_name:"",site_number:"99134",district:"海洋台",address:"小衢山",lon: 122.171,lat: 30.1733,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"横沙岛_新",alias_name:"",site_number:"99137",district:"海洋台",address:"横沙岛_新",lon: 121.849,lat: 31.2978,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"佘山岛",alias_name:"",site_number:"",district:"海洋台",address:"佘山岛",lon: 122.143,lat: 31.2517,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"西马鞍",alias_name:"",site_number:"",district:"海洋台",address:"西马鞍",lon: 122.08,lat: 30.3359,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"九段沙",alias_name:"",site_number:"",district:"浦东",address:"九段沙岛",lon: 121.535,lat: 3112.24,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"三甲港",alias_name:"",site_number:"98603",district:"浦东",address:"三甲港水闸华夏路左转人民塘路",lon: 121.488,lat: 31.1381,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"防汛办",alias_name:"",site_number:"98619",district:"浦东",address:"浦东新区政府5号楼5103防汛办公室",lon: 121.541,lat: 31.2227,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"济阳公园",alias_name:"",site_number:"98611",district:"浦东",address:"济阳路耀华路口公园内",lon: 121.475,lat: 31.1728,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"临空大观园",alias_name:"",site_number:"",district:"浦东",address:"上海地质科普馆内 江镇路近八一河路",lon: 121.464,lat: 31.1048,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"书院镇",alias_name:"",site_number:"98501",district:"浦东",address:"书院镇政府内新府路  3楼主机在经济发展办公室",lon: 121.616,lat: 31.1689,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"周浦",alias_name:"",site_number:"98503",district:"浦东",address:"繁荣路近沪南路校内 主机在门卫值班室",lon: 121.57,lat: 31.1067,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"滴水湖入海闸",alias_name:"",site_number:"98504",district:"浦东",address:"滴水湖河闸南汇嘴观海公园往南上海堤红房子",lon: 121.96,lat: 30.8808,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"临港新城",alias_name:"",site_number:"98521",district:"浦东",address:"滴水湖环湖西一路99号，申港街道派出所后围墙边",lon: 121.552,lat: 30.5418,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"南码头",alias_name:"",site_number:"",district:"浦东",address:"南码头路455号  临沂二小楼顶",lon: 121.302,lat: 31.1148,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"朝阳农场",alias_name:"",site_number:"",district:"浦东",address:"军港公路到朝阳农场海城商店转弯进入",lon: 121.526,lat: 31.0427,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"孙桥",alias_name:"",site_number:"98605",district:"浦东",address:"沔北路185号孙桥现代农业基地",lon: 121.583,lat: 31.3667,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"三林",alias_name:"",site_number:"98607",district:"浦东",address:"三林路53号内小河边 近济阳路",lon: 121.878,lat: 30.9858,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"陆家嘴",alias_name:"",site_number:"98608",district:"浦东",address:"银城中路陆家嘴绿地近世纪大道草坪",lon: 121.304,lat: 31.142,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"薛家泓泵站",alias_name:"",site_number:"98624",district:"浦东",address:"盐朝公路到底后右转有一小岔路不过桥即左转到底",lon: 121.86,lat: 31.1131,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"海通国际",alias_name:"",site_number:"98613",district:"浦东",address:"港口汽车装卸场内庙车公路入内近东川公路",lon: 121.677,lat: 31.32,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"曹路",alias_name:"",site_number:"98614",district:"浦东",address:"新光村村民委员会内 秦家河路132号 华东路入内",lon: 121.655,lat: 31.2622,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"芦潮港",alias_name:"",site_number:"98502",district:"浦东",address:"芦潮港水文站 渔港路到底近高塔",lon: 121.506,lat: 30.5133,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"光明中学",alias_name:"",site_number:"98507",district:"浦东",address:"川南奉公路5468号，近卫亭路 主机位于体育场楼教室办公室内",lon: 121.752,lat: 31.1053,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"航头",alias_name:"",site_number:"98520",district:"浦东",address:"航头社区文化活动中心，航鹤路388号，沪南公路航头路右转，大转盘左转，室外机，西南角变电站旁",lon: 121.592,lat: 31.0261,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"外高桥",alias_name:"",site_number:"98622",district:"浦东",address:"威斯路口上海浦东集装箱码头有限公司办公大楼顶",lon: 121.581,lat: 31.366,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"西沟",alias_name:"",site_number:"98623",district:"浦东",address:"长岛路350号近兰城路西沟水闸内",lon: 121.35,lat: 31.16,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"洋泾",alias_name:"",site_number:"",district:"浦东",address:"沈家弄路891号",lon: 121.321,lat: 31.1416,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"桂家村",alias_name:"",site_number:"98630",district:"浦东",address:"立新船厂保安科室内 近五洲大道",lon: 121.567,lat: 31.3,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"梅园街道",alias_name:"",site_number:"98632",district:"浦东",address:"福山路55号",lon: 121.517,lat: 31.2369,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"祝桥",alias_name:"",site_number:"98515",district:"浦东",address:"祝桥镇卫民村",lon: 121.741,lat: 31.9853,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"大团",alias_name:"",site_number:"98615",district:"浦东",address:"大团高级中学，南芦公路999号门卫值班室",lon: 121.745,lat: 30.9628,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"万祥",alias_name:"",site_number:"98514",district:"浦东",address:"三三公路1811号茂盛路口万祥镇政府",lon: 121.683,lat: 31.2333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"合庆",alias_name:"",site_number:"98625",district:"浦东",address:"人民塘路近奚阳支路",lon: 121.735,lat: 31.2528,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"罗泾镇政府",alias_name:"",site_number:"98309",district:"宝山",address:"飞达路85号西（残联内）",lon: 121.322,lat: 31.4736,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"上大附中",alias_name:"",site_number:"98312",district:"宝山",address:"上大路688号",lon: 121.39,lat: 31.31,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"庙行",alias_name:"",site_number:"98302",district:"宝山",address:"长临路1000号庙行中心小学内",lon: 121.43,lat: 31.3272,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"大场",alias_name:"",site_number:"98303",district:"宝山",address:"华灵路1402号",lon: 121.401,lat: 31.3142,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"农科站",alias_name:"",site_number:"98308",district:"宝山",address:"石太路抚远路口东",lon: 121.345,lat: 31.4333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"罗泾海红村",alias_name:"",site_number:"98310",district:"宝山",address:"陈东路118号",lon: 121.339,lat: 31.4819,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"吴淞",alias_name:"",site_number:"99101",district:"宝山",address:"吴淞海军水文站",lon: 121.509,lat: 31.3925,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"陈家角",alias_name:"",site_number:"98410",district:"闵行",address:"闵行区北翟路陈家角村委会",lon: 121.286,lat: 31.2189,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"交大",alias_name:"",site_number:"98411",district:"闵行",address:"闵行区东川路",lon: 121.423,lat: 31.0231,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"埔江",alias_name:"",site_number:"98412",district:"闵行",address:"闵行区联航路1515号浦江镇政府",lon: 121.526,lat: 31.0656,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"体育公园",alias_name:"",site_number:"98414",district:"闵行",address:"闵行区新镇路",lon: 121.366,lat: 31.1475,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"浦江二小",alias_name:"",site_number:"98415",district:"闵行",address:"闵行区谈中路128号",lon: 121.527,lat: 31.0697,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"浦江三小",alias_name:"",site_number:"98416",district:"闵行",address:"闵行区北环路",lon: 121.517,lat: 31.0997,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"马桥",alias_name:"",site_number:"98401",district:"闵行",address:"闵行区北松路",lon: 121.373,lat: 31.0319,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"华漕",alias_name:"",site_number:"98402",district:"闵行",address:"闵行区联友路",lon: 121.323,lat: 31.2167,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"旗忠村",alias_name:"",site_number:"98421",district:"闵行",address:"闵行区光华路",lon: 121.341,lat: 31.0589,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"梅陇排灌站",alias_name:"",site_number:"98422",district:"闵行",address:"闵行区莘朱路",lon: 121.422,lat: 31.1281,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"吴泾通海路",alias_name:"",site_number:"99105",district:"闵行",address:"闵行区通海路",lon: 121.483,lat: 31.0333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"安亭",alias_name:"",site_number:"98802",district:"嘉定",address:"安亭汽车试车场",lon: 121.161,lat: 31.2956,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"黄渡",alias_name:"",site_number:"",district:"嘉定",address:"黄渡林业站",lon: 121.115,lat: 31.1632,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"真新",alias_name:"",site_number:"98805",district:"嘉定",address:"真新街道",lon: 121.353,lat: 31.2592,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"外岗",alias_name:"",site_number:"98810",district:"嘉定",address:"外岗镇政府",lon: 121.171,lat: 31.3631,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"马桥北管村",alias_name:"",site_number:"98814",district:"嘉定",address:"马桥北管村",lon: 121.321,lat: 31.3333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"南翔",alias_name:"",site_number:"98816",district:"嘉定",address:"南翔镇政府",lon: 121.321,lat: 31.3,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"菊园",alias_name:"",site_number:"",district:"嘉定",address:"菊园街道",lon: 121.15,lat: 31.24,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"浏岛会议中心",alias_name:"",site_number:"",district:"嘉定",address:"浏岛会议中心",lon: 121.14,lat: 31.3,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"周泾",alias_name:"",site_number:"",district:"嘉定",address:"周泾村",lon: 121.08,lat: 31.2,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"朱泾",alias_name:"",site_number:"98107",district:"金山",address:"金山区朱泾镇人民路510号",lon: 121.162,lat: 30.9053,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"漕泾休闲水庄",alias_name:"",site_number:"98109",district:"金山",address:"金山区漕泾休闲水庄",lon: 121.387,lat: 30.8261,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"体育场",alias_name:"",site_number:"98110",district:"金山",address:"金山区体育场",lon: 121.321,lat: 30.7889,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"亭林",alias_name:"",site_number:"98111",district:"金山",address:"金山区亭林工业园区",lon: 121.337,lat: 30.8853,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"松隐",alias_name:"",site_number:"98112",district:"金山",address:"金山区松隐社区育才路100号",lon: 121.233,lat: 30.8939,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"干巷",alias_name:"",site_number:"98113",district:"金山",address:"金山区干巷车镜公园",lon: 121.228,lat: 30.8331,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"钱圩",alias_name:"",site_number:"98114",district:"金山",address:"金山区钱圩工业园区加油站南工厂",lon: 121.242,lat: 30.7883,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"枫泾",alias_name:"",site_number:"98115",district:"金山",address:"金山区枫泾消防队",lon: 121.017,lat: 30.8939,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"廊下",alias_name:"",site_number:"98116",district:"金山",address:"金山区廊下农业园区",lon: 121.146,lat: 30.79,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"张堰",alias_name:"",site_number:"98102",district:"金山",address:"金山区嘉乐金张公路288号",lon: 121.285,lat: 30.8044,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"吕巷",alias_name:"",site_number:"98117",district:"金山",address:"金山区朱吕公路6969号",lon: 121.176,lat: 30.8333,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"叶榭",alias_name:"",site_number:"98203",district:"松江",address:"叶榭镇政府",lon: 121.31,lat: 31.0609,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"五厍",alias_name:"",site_number:"98210",district:"松江",address:"五厍农展馆",lon: 121.264,lat: 31.0842,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"天马山",alias_name:"",site_number:"98212",district:"松江",address:"沈砖公路近新宅路",lon: 121.192,lat: 31.0351,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"小昆山",alias_name:"",site_number:"98202",district:"松江",address:"港业路8号",lon: 121.094,lat: 31.0222,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"泗泾",alias_name:"",site_number:"98209",district:"松江",address:"泗泾镇政府",lon: 121.266,lat: 31.1206,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新桥",alias_name:"",site_number:"98204",district:"松江",address:"新桥镇政府",lon: 121.075,lat: 30.9392,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新浜",alias_name:"",site_number:"98206",district:"松江",address:"华冈路新工路交界",lon: 121.147,lat: 31.0042,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"桐泾",alias_name:"",site_number:"98250",district:"松江",address:"镇政府",lon: 121.137,lat: 31.0806,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"永风街道",alias_name:"",site_number:"98251",district:"松江",address:"镇政府",lon: 121.317,lat: 30.945,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"第一中学",alias_name:"",site_number:"98252",district:"松江",address:"松汇路人民路",lon: 121.231,lat: 31.005,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"松江工业区",alias_name:"",site_number:"98253",district:"松江",address:"江田东路200号",lon: 121.268,lat: 31.0356,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"泰晤士小镇",alias_name:"",site_number:"98254",district:"松江",address:"泰晤士管委会4号楼",lon: 121.113,lat: 31.0206,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"松江镇_荣乐路",alias_name:"",site_number:"99705",district:"松江",address:"荣乐路九峰路口",lon: 121.226,lat: 31.0194,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"淀山湖灯塔",alias_name:"",site_number:"98706",district:"青浦",address:"青浦区金泽镇淀峰村104号淀峰港监圆标",lon: 120.948,lat: 31.1017,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"青东养老院",alias_name:"",site_number:"98707",district:"青浦",address:"青浦区青东农场庆丰路888号健乐颐养院",lon: 121.144,lat: 31.1286,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"淀峰",alias_name:"",site_number:"98710",district:"青浦",address:"青浦区朱家角镇",lon: 120.983,lat: 31.09,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"金泽",alias_name:"",site_number:"98711",district:"青浦",address:"青浦区金泽镇金中路2号广播站",lon: 120.916,lat: 31.0383,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"西岑",alias_name:"",site_number:"98712",district:"青浦",address:"青浦区金泽镇西岑城北支路18号西岑排灌站",lon: 120.956,lat: 31.0703,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"徐泾",alias_name:"",site_number:"98713",district:"青浦",address:"青浦区徐泾镇华徐公路58号徐泾排灌站",lon: 121.276,lat: 31.1733,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"赵巷",alias_name:"",site_number:"98714",district:"青浦",address:"青浦区赵巷镇赵重路128号赵巷排灌站",lon: 121.189,lat: 31.1458,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"重固",alias_name:"",site_number:"98715",district:"青浦",address:"青浦区重固镇福泉路628号重固镇政府",lon: 121.173,lat: 31.2025,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"香花",alias_name:"",site_number:"98716",district:"青浦",address:"青浦区香花街道农园二路水利技术推广站",lon: 121.133,lat: 31.3225,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"赵屯",alias_name:"",site_number:"98717",district:"青浦",address:"青浦区白鹤镇新桥路288号大盈排灌站",lon: 121.078,lat: 31.26,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"小蒸",alias_name:"",site_number:"98718",district:"青浦",address:"区练塘镇蒸西路128号社区中心",lon: 121.074,lat: 30.9894,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"蒸淀",alias_name:"",site_number:"98719",district:"青浦",address:"区练塘镇蒸发路北侧50米现代农业园区管委会",lon: 121.023,lat: 30.9803,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"邬桥",alias_name:"",site_number:"98900",district:"奉贤",address:"邬桥社区办事处",lon: 121.399,lat: 30.96,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"五四农场",alias_name:"",site_number:"98920",district:"奉贤",address:"中港水闸",lon: 121.732,lat: 30.8601,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"海湾751",alias_name:"",site_number:"98903",district:"奉贤",address:"751基地",lon: 121.535,lat: 30.8335,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新寺",alias_name:"",site_number:"98913",district:"奉贤",address:"柘林镇经济发展服务中心",lon: 121.454,lat: 30.8637,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"平安",alias_name:"",site_number:"98914",district:"奉贤",address:"四团镇农业管理科",lon: 121.768,lat: 30.9104,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"跃进农场",alias_name:"",site_number:"98000",district:"崇明",address:"跃进农场场部内草地",lon: 121.222,lat: 31.8114,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"前哨农场",alias_name:"",site_number:"",district:"崇明",address:"前哨农场场办公室屋顶",lon: 121.521,lat: 31.3149,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"长兴岛",alias_name:"",site_number:"98002",district:"崇明",address:"长兴乡乡政府屋顶",lon: 121.69,lat: 31.3919,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"长江大桥码头",alias_name:"",site_number:"",district:"崇明",address:"长江大桥码头门岗屋顶",lon: 121.461,lat: 31.2812,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"长江农场",alias_name:"",site_number:"",district:"崇明",address:"长江农场养老院屋顶",lon: 121.315,lat: 31.4044,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"向化",alias_name:"",site_number:"98014",district:"崇明",address:"向化永冠门岗屋顶",lon: 121.717,lat: 31.5364,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"东滩湿地",alias_name:"",site_number:"99123",district:"崇明",address:"东滩湿地内",lon: 121.959,lat: 31.53,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"新村中学",alias_name:"",site_number:"98007",district:"崇明",address:"新村学校内草地",lon: 121.327,lat: 31.8308,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"闵行",alias_name:"",site_number:"58361",district:"闵行",address:"",lon: 121.38,lat: 31.11,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"宝山",alias_name:"",site_number:"58362",district:"宝山",address:"",lon: 121.46,lat: 31.41,province:"上海",site_type:"基本站",subjection:"气象")
StationInfo.create(name:"嘉定",alias_name:"",site_number:"58365",district:"嘉定",address:"",lon: 121.25,lat: 31.38,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"崇明",alias_name:"",site_number:"58366",district:"崇明",address:"",lon: 121.45,lat: 31.61,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"青浦",alias_name:"",site_number:"58461",district:"青浦",address:"",lon: 121.11,lat: 31.15,province:"上海",site_type:"",subjection:"气象")
StationInfo.create(name:"松江",alias_name:"",site_number:"58462",district:"松江",address:"",lon: 121.25,lat: 31.0,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"奉贤",alias_name:"",site_number:"58463",district:"奉贤",address:"",lon: 121.45,lat: 30.93,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"金山",alias_name:"",site_number:"58460",district:"金山",address:"",lon: 121.16,lat: 30.9,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"浦东",alias_name:"",site_number:"58370",district:"浦东",address:"",lon: 121.56,lat: 31.2259,province:"上海",site_type:"一般站",subjection:"气象")
StationInfo.create(name:"徐家汇",alias_name:"",site_number:"58367",district:"徐家汇",address:"",lon: 121.437,lat: 31.1899,province:"上海",site_type:"一般站",subjection:"气象")
